#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

CCF_SRC=${BF_SRC}/ccf
bf-env "CCF_SRC" "${CCF_SRC}"
bf-env "NGINX_ROOT" "${CCF_SRC}"
