#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

DATA="/data"
bf-env "CCF_DATA" "${DATA}"
bf-env "CCF_CONFIG" "${DATA}/config.yml"
