#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Generate empty config.
#======================================================================================================================

if [ "${CCF_GENERATE_EMPTY_CONFIG}" = "1" ] && [ ! -f "${CCF_CONFIG}" ] ; then
    cp ${NGINX_ROOT}/config-sample.yml ${CCF_CONFIG}
fi
