<?php

namespace Feeds\Pages;

use DateTime;
use Feeds\Config\Config as C;
use Feeds\Helpers\Arr;
use Feeds\Request\Request;

defined("IDX") || die("Nice try.");
Request::is_admin() || Request::redirect("/logout.php");

// handle uploads
if (Request::$method == "POST") {
    $submit = Arr::get($_POST, "submit");

    // handle rota upload
    if ($submit == "rota") {
        // only allow CSV files
        $_FILES["file"]["type"] == "text/csv" || die("You may only upload CSV files.");

        // make sure the name was set
        $name = $_POST["name"];
        if (!$name) die("You must enter the rota name, e.g. 22-2.");

        // get paths
        $tmp_path = $_FILES["file"]["tmp_name"];
        $csv_path = sprintf("%s/%s.csv", C::$dir->rota, $name);

        // move file to the correct location, overwriting whatever is already there
        if (move_uploaded_file($tmp_path, $csv_path)) {
            $success = sprintf("The rota file '%s' was uploaded successfully.", $name);
            unlink(sprintf("%s/rota.cache", C::$dir->cache));
        } else {
            $warning = "Something went wrong uploading the rota file, please try again.";
        }
    }
}

// handle delete CSV file
if ($delete_csv = Arr::get($_GET, "delete_csv")) {
    $path = sprintf("%s/%s", C::$dir->rota, $delete_csv);
    if (file_exists($path)) {
        unlink($path);
        unlink(sprintf("%s/rota.cache", C::$dir->cache));
        $success = sprintf("CSV file '%s' was deleted.", $delete_csv);
    } else {
        $warning = sprintf("Unable to find CSV file '%s'.", $delete_csv);
    }
}

// get uploaded rota files and sort by name
$csv_files = array_slice(scandir(C::$dir->rota), 2);
sort($csv_files);

/**
 * Return a formatted date time string for when the specified rota CSV file was last modified.
 *
 * @param string $file                  File name (without path).
 * @return string                       Formatted last modified string.
 */
function get_csv_modified(string $file): string
{
    $modified = new DateTime("@" . filemtime(sprintf("%s/%s", C::$dir->rota, $file)));
    $modified->setTimezone(C::$events->timezone);
    return $modified->format(C::$formats->sortable_datetime);
}

// output header
$title = "Admin";
require_once("parts/header.php");

?>

<?php if (isset($warning)) : ?>
    <div class="alert alert-warning" role="alert"><?php echo $warning; ?></div>
<?php elseif (isset($success)) : ?>
    <div class="alert alert-success" role="alert"><?php echo $success; ?></div>
<?php endif; ?>

<h2 class="border-bottom"><?php echo $title; ?></h2>
<p>Update settings and upload files.</p>

<h3>Rota</h3>
<p>Upload an rota CSV file here. (For instructions click <a href="javascript:void(0)" data-bs-toggle="modal" data-bs-target="#csv-instructions">here</a>.)</p>
<form class="row row-cols-lg-auto g-3 mb-3 align-items-center needs-validation" method="POST" action="/admin" enctype="multipart/form-data" novalidate>
    <div class="col-12 position-relative">
        <label class="visually-hidden" for="name">Rota Name</label>
        <input type="text" class="form-control" id="name" name="name" placeholder="Name e.g. '22-2'" required />
        <div class="invalid-tooltip">Please enter the rota name.</div>
    </div>
    <div class="col-12 position-relative">
        <label class="visually-hidden" for="file">Rota File</label>
        <input class="form-control" type="file" id="file" name="file" required />
        <div class="invalid-tooltip">Please select a rota CSV file generated by Church Suite.</div>
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-primary" name="submit" value="rota">Upload</button>
    </div>
</form>

<p>The following files are currently uploaded:</p>
<ul>
    <?php foreach ($csv_files as $file) : ?>
        <li>
            <?php echo $file; ?> (last modified <?php echo get_csv_modified($file); ?>)
            <a class="badge rounded-pill text-bg-danger fw-bold" href="/admin/?delete_csv=<?php echo $file; ?>">delete</a>
        </li>
    <?php endforeach; ?>
</ul>

<!-- Generate Church Suite CSV instructions modal -->
<div class="modal fade" id="csv-instructions" tabindex="-1" aria-labelledby="csv-instructions-label" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="csv-instructions-label">Generating Rota CSV File</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h5>Step One</h5>
                <p>Log in to <a href="https://ccsp.churchsuite.com" target="_blank">Church Suite</a>.</p>
                <h5>Step Two</h5>
                <?php $csv_export_link = "https://ccsp.churchsuite.com/modules/rotas/reports/rotas_overview.php?_module=ChurchSuite%5CRotas&_report_name=rotas_overview&_report_view_module=rotas&_report_view_file=rotas_overview&date_start=&date_end=&order_by=name&group_by=service&break_page_on_section=off&show_empty_dates=off&show_members_table=off&page=1"; ?>
                <p>Click <a href="<?php echo $csv_export_link; ?>" target="_blank">here</a> to open the Rota export page.</p>
                <h5>Step Three</h5>
                <p>Select the dates you wish to export - this should cover the entire period of the rota.</p>
                <h5>Step Four</h5>
                <p>Click the 'Generate' button. (This should generate a report showing you every single rota between the dates you selected.)</p>
                <h5>Step Five</h5>
                <p>Hover your mouse over the 'More' button and select 'Download CSV'.</p>
                <h5>Step Six</h5>
                <p>Close this box to return to the main screen, enter the name of the rota (e.g. '22-2'), choose the file you just downloaded, and click the 'Upload' button.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<?php require_once("parts/footer.php"); ?>
