<?php

namespace Feeds\Pages;

use Feeds\Admin\Rota_File;
use Feeds\App;
use Feeds\Config\Config as C;
use Feeds\Helpers\Arr;
use Feeds\Request\Request;

App::check();
Request::is_admin() || Request::redirect("/logout.php");

// handle actions
if (Request::$method == "POST") {
    $result = match (Arr::get($_POST, "submit")) {
        "rota" => Rota_File::upload()
    };
} elseif ($delete_csv = Arr::get($_GET, "delete_csv")) {
    $result = Rota_File::delete($delete_csv);
}

// get uploaded rota files and sort by name
$csv_files = array_slice(scandir(C::$dir->rota), 2);
sort($csv_files);

// output header
$title = "Admin";
require_once("parts/header.php");

?>

<?php if (isset($result)): $alert = $result->success ? "success" : "warning"; ?>
    <div class="alert alert-<?php echo $alert; ?>"><?php echo $result->message; ?></div>
<?php endif; ?>

<h2 class="border-bottom"><?php echo $title; ?></h2>
<p>Update settings and upload files.</p>

<h3>Rota</h3>
<p>Upload an rota CSV file here. (For instructions click <a href="javascript:void(0)" data-bs-toggle="modal" data-bs-target="#csv-instructions">here</a>.)</p>
<form class="row row-cols-lg-auto g-3 mb-3 align-items-center needs-validation" method="POST" action="/admin" enctype="multipart/form-data" novalidate>
    <div class="col-12 position-relative">
        <label class="visually-hidden" for="name">Rota Name</label>
        <input type="text" class="form-control" id="name" name="name" placeholder="Name e.g. '22-2'" required />
        <div class="invalid-tooltip">Please enter the rota name.</div>
    </div>
    <div class="col-12 position-relative">
        <label class="visually-hidden" for="file">Rota File</label>
        <input class="form-control" type="file" id="file" name="file" required />
        <div class="invalid-tooltip">Please select a rota CSV file generated by Church Suite.</div>
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-primary" name="submit" value="rota">Upload</button>
    </div>
</form>

<p>The following files are currently uploaded:</p>
<ul>
    <?php foreach ($csv_files as $file) : ?>
        <li>
            <?php echo $file; ?> (last modified <?php echo Rota_File::get_last_modified($file); ?>)
            <a class="badge rounded-pill text-bg-danger fw-bold" href="/admin/?delete_csv=<?php echo $file; ?>">delete</a>
        </li>
    <?php endforeach; ?>
</ul>

<!-- Generate Church Suite CSV instructions modal -->
<div class="modal fade" id="csv-instructions" tabindex="-1" aria-labelledby="csv-instructions-label" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="csv-instructions-label">Generating Rota CSV File</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h5>Step One</h5>
                <p>Log in to <a href="https://ccsp.churchsuite.com" target="_blank">Church Suite</a>.</p>
                <h5>Step Two</h5>
                <?php $csv_export_link = "https://ccsp.churchsuite.com/modules/rotas/reports/rotas_overview.php?_module=ChurchSuite%5CRotas&_report_name=rotas_overview&_report_view_module=rotas&_report_view_file=rotas_overview&date_start=&date_end=&order_by=name&group_by=service&break_page_on_section=off&show_empty_dates=off&show_members_table=off&page=1"; ?>
                <p>Click <a href="<?php echo $csv_export_link; ?>" target="_blank">here</a> to open the Rota export page.</p>
                <h5>Step Three</h5>
                <p>Select the dates you wish to export - this should cover the entire period of the rota.</p>
                <h5>Step Four</h5>
                <p>Click the 'Generate' button. (This should generate a report showing you every single rota between the dates you selected.)</p>
                <h5>Step Five</h5>
                <p>Hover your mouse over the 'More' button and select 'Download CSV'.</p>
                <h5>Step Six</h5>
                <p>Close this box to return to the main screen, enter the name of the rota (e.g. '22-2'), choose the file you just downloaded, and click the 'Upload' button.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<?php require_once("parts/footer.php"); ?>
