<?php

namespace Feeds\Pages;

use Feeds\Admin\Prayer_File;
use Feeds\Admin\Rota_File;
use Feeds\App;
use Feeds\Config\Config as C;
use Feeds\Helpers\Arr;
use Feeds\Request\Request;

App::check();
Request::is_admin() || Request::redirect("/logout.php");

// handle actions
if (Request::$method == "POST") {
    $result = match (Arr::get($_POST, "submit")) {
        "prayer-adults" => Prayer_File::upload_adults(),
        "prayer-children" => Prayer_File::upload_children(),
        "rota" => Rota_File::upload()
    };
} elseif ($delete_rota = Arr::get($_GET, "delete_rota")) {
    $result = Rota_File::delete($delete_rota);
}

// get uploaded rota files and sort by name
$rota_files = array_slice(scandir(C::$dir->rota), 2);
sort($rota_files);

// get uploaded prayer calendar files and sort by name
$prayer_files = array_map("basename", glob(sprintf("%s/*.csv", C::$dir->prayer), 2));
sort($prayer_files);

// store Church Suite links
$rota_export_href = "https://ccsp.churchsuite.com/modules/addressbook/reports/contact_table_generator.php?key_dates%5B%5D=&order=name&order_direction=asc&page=1&_module=ChurchSuite%5CAddressBook&_report_name=contact_table_generator&_report_view_module=addressbook&_report_view_file=contact_table_generator&columns%5B%5D=first_name&columns%5B%5D=last_name&date_start=2022-05-23&date_end=2022-08-23&tags_match=any&tags%5B%5D=30&status=active";
$prayer_calendar_adults_export_href = "https://ccsp.churchsuite.com/modules/addressbook/reports/contact_table_generator.php?key_dates%5B%5D=&order=name&order_direction=asc&page=1&_module=ChurchSuite%5CAddressBook&_report_name=contact_table_generator&_report_view_module=addressbook&_report_view_file=contact_table_generator&columns%5B%5D=first_name&columns%5B%5D=last_name&date_start=2022-05-23&date_end=2022-08-23&tags_match=any&tags%5B%5D=30&status=active";
$prayer_calendar_children_export_href = "https://ccsp.churchsuite.com/modules/children/reports/child_table_generator.php?key_dates%5B%5D=&order=name&order_direction=asc&page=1&_module=ChurchSuite%5CChildren&_report_name=child_table_generator&_report_view_module=children&_report_view_file=child_table_generator&columns%5B%5D=first_name&columns%5B%5D=last_name&date_start=&date_end=&group=&tags_match=any&tags%5B%5D=31&status=active";

// output header
$title = "Upload";
$subtitle = "Use this page to upload and update CSV files generated by Church Suite.";
require_once("parts/header.php");

// output alert
require_once("parts/alert.php"); ?>

<!-- Rota file upload -->
<h2>Rota</h2>
<p>Upload a rota CSV file here. (For instructions click <a href="javascript:void(0)" data-bs-toggle="modal" data-bs-target="#rota-instructions">here</a>.)</p>
<form class="row row-cols-md-auto g-3 mb-3 align-items-center needs-validation" method="POST" action="/upload" enctype="multipart/form-data" novalidate>
    <div class="col-12 position-relative">
        <label class="visually-hidden" for="name">Rota Name</label>
        <input type="text" class="form-control" id="name" name="name" placeholder="Name e.g. '22-2'" required />
        <div class="invalid-tooltip">Please enter the rota name.</div>
    </div>
    <div class="col-12 position-relative">
        <label class="visually-hidden" for="file-rota">Rota File</label>
        <input class="form-control" type="file" id="file-rota" name="file" required />
        <div class="invalid-tooltip">Please select a rota CSV file generated by Church Suite.</div>
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-primary" name="submit" value="rota">Upload</button>
    </div>
</form>

<p>The following files are currently uploaded:</p>
<ul>
    <?php foreach ($rota_files as $file) : ?>
        <li>
            <?php echo $file; ?> (last modified <?php echo Rota_File::get_last_modified($file); ?>)
            <a class="badge rounded-pill text-bg-danger fw-bold check-first" href="/upload/?delete_rota=<?php echo $file; ?>">delete</a>
        </li>
    <?php endforeach; ?>
</ul>

<!-- Prayer Calendar file upload -->
<h2>Prayer Calendar</h2>
<p>Upload prayer calendar CSV files here. (For instructions click <a href="javascript:void(0)" data-bs-toggle="modal" data-bs-target="#prayer-calendar-instructions">here</a>.)</p>
<form class="row row-cols-sm-auto g-3 mb-3 align-items-center needs-validation" method="POST" action="/upload" enctype="multipart/form-data" novalidate>
    <div class="col-12">
        <input type="text" readonly class="form-control-plaintext" value="Adults" />
    </div>
    <div class="col-12 position-relative">
        <label class="visually-hidden" for="file-prayer-adults">Rota File</label>
        <input class="form-control" type="file" id="file-prayer-adults" name="file" required />
        <div class="invalid-tooltip">Please select an adults prayer calendar CSV file generated by Church Suite.</div>
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-primary" name="submit" value="prayer-adults">Upload</button>
    </div>
</form>
<form class="row row-cols-sm-auto g-3 mb-3 align-items-center needs-validation" method="POST" action="/upload" enctype="multipart/form-data" novalidate>
    <div class="col-12">
        <input type="text" readonly class="form-control-plaintext" value="Children" />
    </div>
    <div class="col-12 position-relative">
        <label class="visually-hidden" for="file-prayer-children">Rota File</label>
        <input class="form-control" type="file" id="file-prayer-children" name="file" required />
        <div class="invalid-tooltip">Please select a children prayer calendar CSV file generated by Church Suite.</div>
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-primary" name="submit" value="prayer-children">Upload</button>
    </div>
</form>

<?php if ($prayer_files) : ?>
    <p>The following files are currently uploaded:</p>
    <ul>
        <?php foreach ($prayer_files as $file) : ?>
            <li>
                <?php echo $file; ?> (last modified <?php echo Prayer_File::get_last_modified($file); ?>)
                <a class="badge rounded-pill text-bg-danger fw-bold check-first" href="/upload/?delete_prayer=<?php echo $file; ?>">delete</a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>

<!-- Generate Church Suite rota feed instructions modal -->
<div class="modal fade" id="rota-instructions" tabindex="-1" aria-labelledby="rota-instructions-label" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="rota-instructions-label">Generating Rota CSV File</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h5>Step One</h5>
                <p>Log in to <a href="https://ccsp.churchsuite.com" target="_blank">Church Suite</a>.</p>
                <h5>Step Two</h5>
                <p>Click <a href="<?php echo $rota_export_href; ?>" target="_blank">here</a> to open the export page for the rota.</p>
                <h5>Step Three</h5>
                <p>Select the dates you wish to export - this should cover the entire period of the rota.</p>
                <h5>Step Four</h5>
                <p>Click the 'Generate' button. (This should generate a report showing you every single rota between the dates you selected.)</p>
                <h5>Step Five</h5>
                <p>Hover your mouse over the 'More' button and select 'Download CSV'.</p>
                <h5>Step Six</h5>
                <p>Close this box to return to the main screen, enter the name of the rota (e.g. '22-2'), choose the file you just downloaded, and click the 'Upload' button.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Generate Church Suite prayer calendar feed instructions modal -->
<div class="modal fade" id="prayer-calendar-instructions" tabindex="-1" aria-labelledby="prayer-calendar-instructions-label" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="prayer-calendar-instructions-label">Generating Prayer Calendar CSV File</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h5>Step One</h5>
                <p>Log in to <a href="https://ccsp.churchsuite.com" target="_blank">Church Suite</a>.</p>
                <h5>Step Two</h5>
                <p>Click <a href="<?php echo $prayer_calendar_adults_export_href; ?>" target="_blank">here</a> to open the export page for adults.<br />
                    Click <a href="<?php echo $prayer_calendar_children_export_href; ?>" target="_blank">here</a> to open the export page for children.</p>
                <h5>Step Three</h5>
                <p>Hover your mouse over the 'More' button and select 'Download CSV'.</p>
                <h5>Step Four</h5>
                <p>Close this box to return to the main screen, choose the file you just downloaded, and click the 'Upload' button.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<?php require_once("parts/footer.php"); ?>

